
image: Visual Studio 2017
configuration: AppVeyor
platform: Any CPU
skip_tags: true

matrix:
  fast_finish: true

environment:
  mdix_version: 2.5.1
  mdix_mahapps_version: 0.0.13
  RestorePackages: false
  matrix:
    - current_version: $(mdix_version)
    - current_version: $(mdix_mahapps_version)

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(current_version).{build}'
  assembly_file_version: '$(current_version).{build}'
  assembly_informational_version: '$(current_version).{build}'
before_build:
- ps: .paket\paket.exe restore
build:
  project: MaterialDesignToolkit.Wpf.sln
  verbosity: minimal
after_build:
- ps: If ($env:current_version -eq $env:mdix_version) nuget pack MaterialDesignThemes.nuspec -Version $env:current_version
- ps: If ($env:current_version -eq $env:mdix_mahapps_version) nuget pack MaterialDesignThemes.MahApps.nuspec -Version $env:current_version
- ps: If ($env:current_version -eq $env:mdix_version) 7z a Demo.$(env:current_version).zip MainDemo.Wpf\bin\**\*.*
artifacts:
- path: '**\MaterialDesignThemes.*.nupkg'
- path: Demo.*.zip


for:
-
  branches:
    only:
      - master
  version: $(mdix_version)-ci{build}
#  deploy:
#  - provider: NuGet
#    api_key:
#      secure: B+WIdbRYr/rJo1QMeDwNen2xcj4RTu1d8AZiA03kb8wsWZVQxt5OgsWRacmEjWRd
#    artifact: MaterialDesignThemes.*.nupkg

-
  branches:
    only:
      - release
  version: $(mdix_version).{build}
